import { RoundButton } from 'components/button';
import Card from 'components/Card';
import Intro from 'components/Intro';
import Profile from 'components/Profile';
import { H1, Paragraph } from 'components/text';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Row, Col } from 'react-grid-system';

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Intro>
                <Container>
                    <Row>
                        <Col
                            md={3}
                            offset={{
                                md: 2
                            }}
                        >
                            <Profile />
                        </Col>
                        <Col
                            md={5}
                            offset={{
                                md: 2
                            }}
                        >
                            <H1>Bart Koelewijn</H1>
                            <Paragraph>
                                Een brug tussen vormgeving en keiharde code. Hij zorgt dat de boel gesmeerd loopt, maar ook dat alles er
                                strak, consistent en mooi uitziet.
                            </Paragraph>
                            <RoundButton />
                        </Col>
                    </Row>
                </Container>
            </Intro>
            <Container>
                <Row>
                    <Col
                        md={4}
                        offset={{
                            md: 1
                        }}
                    >
                        <Card variant="blue" lightVariant="lightBlue" title="Awaretrain" />
                    </Col>
                    <Col
                        md={4}
                        offset={{
                            md: 1
                        }}
                    >
                        <Paragraph>
                            Awaretrain realiseert bewustwording en gedragsverandering binnen de werkomgeving door middel van een nieuwe
                            ‘teaser’ app.
                        </Paragraph>
                        <Paragraph>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                            magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat.
                        </Paragraph>
                    </Col>
                    <Col md={2} />
                </Row>
                <Row>
                    <Col md={4}>
                        <Paragraph>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                            magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
                            laborum.
                        </Paragraph>
                    </Col>
                    <Col
                        md={7}
                        offset={{
                            md: 1
                        }}
                    >
                        <Card variant="green" lightVariant="lightGreen" title="Cycle Center 53-11" />
                    </Col>
                </Row>
            </Container>
        </>
    );
};

export default Home;
