import Badge from 'components/Badge';
import { RoundButton } from 'components/button';
import Card from 'components/Card';
import Dots from 'components/Dots';
import { FormSwitch } from 'components/form';
import Intro from 'components/Intro';
import IntroCta from 'components/IntroCta';
import Profile from 'components/Profile';
import { SectionAwaretrain } from 'components/section';
import { H1, Paragraph } from 'components/text';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useThemeContext } from 'providers/ThemeProvider';
import { Container, Row, Col } from 'react-grid-system';

const Home: NextPage = () => {
    const { isDark, setIsDark } = useThemeContext();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <FormSwitch checked={isDark} onChange={(event) => setIsDark(event.target.checked)} />
            <Intro>
                <Container>
                    <Row>
                        <Col
                            md={3}
                            offset={{
                                md: 2
                            }}
                        >
                            <Profile />
                        </Col>
                        <Col
                            md={5}
                            offset={{
                                md: 2
                            }}
                        >
                            <H1>Bart Koelewijn</H1>
                            <Paragraph noMargin>
                                Een brug tussen vormgeving en keiharde code. Hij zorgt dat de boel gesmeerd loopt, maar ook dat alles er
                                strak, consistent en mooi uitziet.
                            </Paragraph>
                            <IntroCta />
                        </Col>
                    </Row>
                </Container>
            </Intro>
            <Container>
                <SectionAwaretrain variant="blue" lightVariant="lightBlue" title="Awaretrain">
                    <Paragraph>
                        Awaretrain realiseert bewustwording en gedragsverandering binnen de werkomgeving door middel van een nieuwe ‘teaser’
                        app.
                    </Paragraph>
                    <Paragraph>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna
                        aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                    </Paragraph>
                    <Badge variant="blue" lightVariant="lightBlue" />
                </SectionAwaretrain>
                <Row>
                    <Col md={4}>
                        <Paragraph>
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
                            magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
                            consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                            pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
                            laborum.
                        </Paragraph>
                    </Col>
                    <Col
                        md={7}
                        offset={{
                            md: 1
                        }}
                    >
                        <Card variant="green" lightVariant="lightGreen" title="Cycle Center 53-11" />
                    </Col>
                </Row>
            </Container>
        </>
    );
};

export default Home;
